#!/bin/bash
# Setup .env file for test harness
# Creates .env in project root with correct MySQL configuration

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

echo "🔧 Setting up test harness .env file"
echo "===================================="
echo ""

if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env file already exists at $ENV_FILE"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env file"
        exit 0
    fi
fi

# Test MySQL connection to determine password
echo "Testing MySQL connection..."
echo "Trying common passwords..."

MYSQL_PASSWORD=""
MYSQL_PORT=3307

# Try Docker MySQL password first
if mysql -h localhost -P 3307 -u root -ppassword -e "SELECT 1;" 2>/dev/null; then
    MYSQL_PASSWORD="password"
    echo "✅ MySQL Docker connection successful (password: 'password')"
elif mysql -h localhost -P 3306 -u root -e "SELECT 1;" 2>/dev/null; then
    MYSQL_PASSWORD=""
    MYSQL_PORT=3306
    echo "✅ MySQL local connection successful (no password)"
elif mysql -h localhost -P 3306 -u root -proot -e "SELECT 1;" 2>/dev/null; then
    MYSQL_PASSWORD="root"
    MYSQL_PORT=3306
    echo "✅ MySQL local connection successful (password: 'root')"
else
    echo "⚠️  Could not automatically determine MySQL password"
    echo ""
    read -p "Is MySQL running in Docker? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        MYSQL_PASSWORD="password"
        MYSQL_PORT=3307
        echo "Using Docker MySQL defaults (port 3307, password 'password')"
    else
        read -p "Enter MySQL root password (or press Enter for no password): " MYSQL_PASSWORD
        read -p "Enter MySQL port (default 3306): " MYSQL_PORT_INPUT
        if [ ! -z "$MYSQL_PORT_INPUT" ]; then
            MYSQL_PORT=$MYSQL_PORT_INPUT
        fi
    fi
fi

# Create .env file
cat > "$ENV_FILE" <<EOF
# Test Harness Configuration
# Generated by setup_env.sh

# API Gateway
API_GATEWAY_URL=http://localhost:3000

# AI Service
AI_SERVICE_URL=http://localhost:8000

# MySQL Configuration
MYSQL_HOST=localhost
MYSQL_PORT=${MYSQL_PORT}
MYSQL_USER=root
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MYSQL_DB_USERS=kayak_users
MYSQL_DB_BOOKINGS=kayak_bookings
MYSQL_DB_BILLING=kayak_billing

# MongoDB Configuration
MONGO_URI=mongodb://localhost:27017
MONGO_DB=kayak_doc
MONGO_DB_SEARCH=kayak_search

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_DB=0

# Kafka Configuration
KAFKA_BOOTSTRAP_SERVERS=localhost:9092

# JWT Configuration
JWT_SECRET=super-secret-key-change-in-production
EOF

echo ""
echo "✅ Created .env file at: $ENV_FILE"
echo ""
echo "📝 Configuration:"
echo "   MySQL Port: $MYSQL_PORT"
echo "   MySQL Password: ${MYSQL_PASSWORD:-'(empty)'}"
echo ""
echo "You can now run tests with:"
echo "   python test_harness/run_tests.py"

