apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kayak-gateway
  namespace: kayak
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: kayak.local
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3000
          - path: /ai/?(.*)
            pathType: Prefix
            backend:
              service:
                name: ai-service
                port:
                  number: 8000
